version: "3.6"
services:
  web:
    build: .
    container_name: phpapp
    ports:
      - "0.0.0.0:8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: phpapp
    volumes:
      - db_data:/var/lib/mysql
      - ./src/database.sql:/docker-entrypoint-initdb.d/database.sql
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf

volumes:
  db_data: